// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace ProductMicroservice.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221002101858_FridgeDb")]
    partial class FridgeDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Repositories.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47bd05d-53f0-4857-93d4-2e8dd396c09a"),
                            CreatedDate = new DateTime(2022, 10, 2, 10, 18, 58, 28, DateTimeKind.Utc).AddTicks(5406),
                            LinkImage = "https://craves.everybodyshops.com/wp-content/uploads/ThinkstockPhotos-535489242-1024x683@2x.jpg",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("0d8e0c4f-d158-49c0-aab4-4595e23d4c33"),
                            CreatedDate = new DateTime(2022, 10, 2, 10, 18, 58, 28, DateTimeKind.Utc).AddTicks(5408),
                            LinkImage = "https://www.expatica.com/app/uploads/sites/2/2014/05/bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("fd33edbb-fb43-433c-865d-6402e01654d3"),
                            CreatedDate = new DateTime(2022, 10, 2, 10, 18, 58, 28, DateTimeKind.Utc).AddTicks(5409),
                            LinkImage = "https://images5.alphacoders.com/102/1022723.jpg",
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("d06ea4d3-88ae-4316-84aa-210e5abcb553"),
                            CreatedDate = new DateTime(2022, 10, 2, 10, 18, 58, 28, DateTimeKind.Utc).AddTicks(5410),
                            LinkImage = "https://pm1.narvii.com/6810/05dbd7aaebf3454313b99edfd566b06356a59be3v2_hq.jpg",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("c5fbace4-df51-49de-a599-66d369011b20"),
                            CreatedDate = new DateTime(2022, 10, 2, 10, 18, 58, 28, DateTimeKind.Utc).AddTicks(5412),
                            LinkImage = "https://g.foolcdn.com/image/?url=https%3A//g.foolcdn.com/editorial/images/218648/eggs-brown-getty_BSCxkDW.jpg&w=2000&op=resize",
                            Name = "Egg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
