// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace ProductMicroservice.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Repositories.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab8a02d5-95d2-4c7b-b1e8-d70a048d98e2"),
                            CreatedDate = new DateTime(2022, 12, 15, 9, 11, 18, 515, DateTimeKind.Utc).AddTicks(7243),
                            LinkImage = "https://craves.everybodyshops.com/wp-content/uploads/ThinkstockPhotos-535489242-1024x683@2x.jpg",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("4dabfde6-b155-4e93-a510-c8fdd502ef83"),
                            CreatedDate = new DateTime(2022, 12, 15, 9, 11, 18, 515, DateTimeKind.Utc).AddTicks(7249),
                            LinkImage = "https://www.expatica.com/app/uploads/sites/2/2014/05/bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("67784688-8ca1-4e6a-a773-2831db0e16dc"),
                            CreatedDate = new DateTime(2022, 12, 15, 9, 11, 18, 515, DateTimeKind.Utc).AddTicks(7250),
                            LinkImage = "https://images5.alphacoders.com/102/1022723.jpg",
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("62e23a7a-b659-4a9f-a417-3355ae4b1d80"),
                            CreatedDate = new DateTime(2022, 12, 15, 9, 11, 18, 515, DateTimeKind.Utc).AddTicks(7251),
                            LinkImage = "https://pm1.narvii.com/6810/05dbd7aaebf3454313b99edfd566b06356a59be3v2_hq.jpg",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("aed0c7d8-18ed-4945-9d8b-cc3a0e7a92be"),
                            CreatedDate = new DateTime(2022, 12, 15, 9, 11, 18, 515, DateTimeKind.Utc).AddTicks(7252),
                            LinkImage = "https://g.foolcdn.com/image/?url=https%3A//g.foolcdn.com/editorial/images/218648/eggs-brown-getty_BSCxkDW.jpg&w=2000&op=resize",
                            Name = "Egg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
