// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace ProductMicroservice.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Repositories.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96069b0b-b9ff-491d-8f8c-bdf159753e0c"),
                            CreatedDate = new DateTime(2022, 10, 14, 7, 15, 18, 885, DateTimeKind.Utc).AddTicks(6473),
                            LinkImage = "https://craves.everybodyshops.com/wp-content/uploads/ThinkstockPhotos-535489242-1024x683@2x.jpg",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("02f0ccb6-bff0-4b77-a1a5-1c6e331bb89b"),
                            CreatedDate = new DateTime(2022, 10, 14, 7, 15, 18, 885, DateTimeKind.Utc).AddTicks(6482),
                            LinkImage = "https://www.expatica.com/app/uploads/sites/2/2014/05/bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("8bac0be8-4af8-475a-b1eb-99bca1cc9b5f"),
                            CreatedDate = new DateTime(2022, 10, 14, 7, 15, 18, 885, DateTimeKind.Utc).AddTicks(6483),
                            LinkImage = "https://images5.alphacoders.com/102/1022723.jpg",
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("a9ba8e48-cd41-4b8d-acd0-fb8d257b24bc"),
                            CreatedDate = new DateTime(2022, 10, 14, 7, 15, 18, 885, DateTimeKind.Utc).AddTicks(6484),
                            LinkImage = "https://pm1.narvii.com/6810/05dbd7aaebf3454313b99edfd566b06356a59be3v2_hq.jpg",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("67408836-035b-4fe3-b877-991a8d2f3560"),
                            CreatedDate = new DateTime(2022, 10, 14, 7, 15, 18, 885, DateTimeKind.Utc).AddTicks(6485),
                            LinkImage = "https://g.foolcdn.com/image/?url=https%3A//g.foolcdn.com/editorial/images/218648/eggs-brown-getty_BSCxkDW.jpg&w=2000&op=resize",
                            Name = "Egg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
